name: CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install_system
        run: |
          sudo apt update
          sudo apt install libgtest-dev
          sudo apt install cmake
          sudo apt install make
          sudo apt install libgmock-dev
          sudo apt install lcov
          sudo apt install valgrind
          sudo apt install clang-format
          sudo apt install cppcheck
          sudo apt install clang-tidy
          sudo pip install cpplint
          sudo apt install python
      - name: check
        run: bash preprocess_code.sh
      - name: build_all
        run: bash build.sh
      - name: run_test
        run: bash run_test_suite.sh
      - name: publish_coverage_report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: ./build/test/unit/coverage_report
